[workspace]
members = ["examples/*"]
resolver = "2"

[package]
name = "parity_enum"
version = "0.1.0-alpha"
edition = "2024"
rust-version = "1.87"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.104", features = ["span-locations"] }
quote = "1.0.42"
syn = { version = "2.0.111", features = ["extra-traits", "fold", "full", "visit"] }

[dev-dependencies]
itertools = "0.14.0"
trybuild = { version = ">=1.0", features = ["diff"] }

